### ISSUE TITLE
No such file or directory: 'xxx/multirun/xxx/0/main.py'

### ISSUE THREAD

**Issue by JinfenLi** [facebookresearch/UNIREX#3]
I don't have a such error in Windows but in Linux

**Comment by aarzchan** [comment]
Hi @JinfenLi, thanks for reaching out!

To help me debug this issue, could you please share the following items:
- The command that you're running.
- The path that you're running the command from.
- A screenshot of your full error message and stack trace.
- The yaml file for your conda environment.

**Comment by JinfenLi** [comment]
Hi Aaron,
The problem is solved after I reinstalled the correct version of Pytorch. However, I tried to run the model with RTX 2080 and RTX A6000 respectively (I use the same code with the same settings with the batch size of 2), the former took around 12 minutes to finish one epoch but the latter took 88 hours. Even if I increase the batch size to 64 on RTX A6000, it still takes 2.5 hours.
I am not sure what happened. Could you enlighten me what GPU are you using? Thanks!


Jinfen Li

PhD student

***@***.***
School of Information Studies

Syracuse University

________________________________

**Comment by aarzchan** [comment]
I used NVIDIA A100 40GB GPUs for my experiments.

The training time also depends a lot on the training method and the dataset. Which settings are you reporting these numbers for?

**Comment by aarzchan** [comment]
Hi @JinfenLi, do you still have any questions about this? If not, we can close this issue. Thanks!

**Comment by JinfenLi** [comment]
Everything works on my side, thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
